### ISSUE TITLE
Responsive `width`

### ISSUE THREAD

**Issue by zverbatim** [CookPete/react-player#145]
Hi,
Is it possible to make the `<ReactPlayer>` `width` responsive?
For example to inherit the width of the `div` or `td` in which is placed?
Thanks

**Comment by CookPete** [comment]
You should be able to pass `100%` to the `width` and `height` props and it will fill it's container. If you want responsive width and aspect ratio, do something like this:

```css
$player-ratio: 1280 / 720;

.playerWrapper {
  position: relative;
  padding-top: 100% / $player-ratio;
}

.player {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
```

```js 
<div className='wrapper'>
  <ReactPlayer
    className='player'
    playing
    url={...}
    width='100%'
    height='100%'
  />
</div>
```
