### ISSUE TITLE
Does not hide the youtube suggestion videos

### ISSUE THREAD

**Issue by rasel-stacklearner** [cookpete/react-player#1844]
#### Current Behavior
It does not hide the video suggestion part. 
<img width="350" alt="image" src="https://github.com/cookpete/react-player/assets/141147182/5f6c27df-903f-41e3-83b7-628961a0e46c">

#### Expected Behavior
 I explicitly configured the player to hide the related YouTube videos; therefore, it should not display them. 

```js
<ReactPlayer
            ref={videoRef}
            style={{
              position: "absolute",
              top: 0,
              left: 0,
              right: 0,
              bottom: 0,
              pointerEvents: "none",
            }}
            width={"100%"}
            height={"100%"}
            url={state.url ?? ""}
            controls={false}
            playing={state.settings.playing}
            playbackRate={state.settings.playbackSpeed}
            onPlaybackRateChange={handleOnPlaybackRateChange}
            volume={state.settings.volume}
            onEnded={handleVideoEnd}
            onProgress={handleOnProgress}
            config={{
              youtube: {
                playerVars: {
                  rel: 0,
                },
              },
            }}
            light={false}
          />
```

#### Environment
- URL attempting to play: https://www.youtube.com/watch?v=orn9N90dcVY&t=5372s
- Browser: Chrome
- Operating system: Mac

**Comment by k2fx** [comment]
The behavior for the _rel_ parameter changed after September 25, 2018. The effect of the change is that you will not be able to disable related videos. [via](https://developers.google.com/youtube/player_parameters#august-23,-2018)

**Comment by luwes** [comment]
thanks @k2fx, it's not possible to hide unfortunately.

**Comment by nicokimmel** [comment]
It is possible with some CSS hack if you also want to hide the default YouTube player controls.

```SCSS
.wrapper {
    width: 100%;
    height: 100%;
    overflow: hidden;
    
    iframe {
        position: absolute;
        top: -200px;
        bottom: -200px;
        height: calc(100% + 2 * 200px);
        pointer-events: none;
        aspect-ratio: 16/9;
    }
}
```
