### ISSUE TITLE
Issues with url parsing

### ISSUE THREAD

**Issue by explodingcamera** [CookPete/react-player#548]
In my current setup, media url's don't actually have a file extension and use the Content-Type Header.
React-Player has some Regex's that check for the file extension, so I'm not abe to play these url's.

As a workaround, I currently have to append something like `?fakeFileExtension=.mp4`.
This is a kind of dirty workaround, but fails if I try to use the Media Fragments by adding something like `#t=10` at the end of my url.

**Comment by CookPete** [comment]
What URL/media type are you trying to play? ReactPlayer should fallback to using a plain `<video>` if it can't match a URL to a specific player.

**Comment by explodingcamera** [comment]
I've tried both webm and mp4's served from s3 and ReactPlayer doesn't render anything. 

e.g this works:
https://cdn.canx.network/media/s3/wasabi/canx-1/19408686ecca446dd088c5de6863f7c584e894af857066432262378641953b3286d050800e829622e4a634885c11d364a0e060e714e1a64f1f452fb933e6339d6227?fakeFileExtension=.mp4

but this doesn't:
https://cdn.canx.network/media/s3/wasabi/canx-1/19408686ecca446dd088c5de6863f7c584e894af857066432262378641953b3286d050800e829622e4a634885c11d364a0e060e714e1a64f1f452fb933e6339d6227#t=0

```yaml
Accept-Ranges: bytes
Content-Length: 10498677
Content-Type: video/mp4
Date: Mon, 07 Jan 2019 12:37:40 GMT
Server: nginx/1.15.6
Vary: Origin
```
