### ISSUE TITLE
Cover video

### ISSUE THREAD

**Issue by markolofsen** [CookPete/react-player#629]
How to make covering video like `backgroundSize: cover`?
I tried but each video has own aspect ratios.

**Comment by CookPete** [comment]
This guys seems to have cracked it: https://codepen.io/AllThingsSmitty/pen/NbLLjb

```css
video {
  left: 50%;
  min-height: 100%;
  min-width: 100%;
  position: absolute;
  top: 50%;
  transform: translate(-50%, -50%);
}
```
